# docker-compose.yml
version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=scrapy_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrapy_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: